### ISSUE TITLE
pdftohtml does not create any scanned page with formats png and jpg

### ISSUE THREAD

**Issue by salmansamie** [WZBSocialScienceCenter/pdftabextract#6]
I tried to extract table data from PDF files but the first step in the process is to generate xml and page images. 

Unfortunately, using pdftohtml library for PDF pages I cannot create any image files in the data/ directory when following the tutorial at: [DataMining- WZBSocialScienceCenter](https://datascience.blog.wzb.eu/2017/02/16/data-mining-ocr-pdfs-using-pdftabextract-to-liberate-tabular-data-from-scanned-documents/#more-384)

The command that fails to create the images:

> pdftohtml -c -xml -hidden TradingIEX.pdf TradingIEX.pdf.xml

How is it possible to create such page images for the non-scanned PDF files?

Thanks.

**Comment by internaut** [comment]
Please note that this is a bug-tracker for pdftabextract. It is neither a help forum, nor a bug-tracker for pdftohtml, hence I will be closing this issue because it has nothing to do with pdftabextract.

Regarding your problem, I cannot help you. The command seems correct, so it probably has to do with your PDFs.
